apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
  - name: init-container
    image: busybox
    volumeMounts:
    - name: homework-volume
      mountPath: /init
    command: ["/bin/sh", "-c"]
    args:
    - mkdir -p /init && echo 'Hello, World!' > /init/index.html && sleep 3600
  - name: cleanup-container
    image: busybox
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
    command: ["/bin/sh", "-c"]
    args:
    - rm /homework/index.html && sleep 3600
  volumes:
  - name: homework-volume
    emptyDir: {}
